/* Chango Programming section — course catalog */
var PROGRAMMING_COURSES = [
  {
    id: 'backend',
    title: 'Backend Developer Roadmap',
    status: 'available',
    icon: '🖥️',
    grad: 'linear-gradient(135deg, #8B5CF6, #6C3CE1)',
    tint: 'rgba(139, 92, 246, 0.15)',
    border: 'rgba(139, 92, 246, 0.4)',
    tagline: 'The flagship path. Learn the real backend stack: PHP, Laravel, SQL, APIs, Docker and deployment.',
    desc: 'From your very first line of code to a job-ready backend developer. Follow the path: Learn → Practice → Build → Prove → Become Job Ready.',
    meta: [{ label: '12 Levels', value: 'Full Roadmap' }, { label: '68+ Lessons', value: 'Structured' }, { label: '6 Projects', value: 'Real-world' }],
    href: 'backend/backend.html',
    cta: 'Start the Roadmap',
    soonNote: null
  },
  {
    id: 'frontend',
    title: 'Frontend Developer Roadmap',
    status: 'coming-soon',
    icon: '🎨',
    grad: 'linear-gradient(135deg, #22D3EE, #3B82F6)',
    tint: 'rgba(34, 211, 238, 0.12)',
    border: 'rgba(34, 211, 238, 0.35)',
    tagline: 'HTML, CSS, JavaScript, and modern UI frameworks — everything you need to build beautiful interfaces.',
    desc: 'The complete frontend path: markup, styling, interactivity, component frameworks, and real UI projects. Every pixel explained, no magic.',
    meta: [{ label: '10+ Levels', value: 'Structured' }, { label: '60+ Lessons', value: 'Planned' }],
    href: null,
    cta: 'Coming Soon',
    soonNote: null
  },
  {
    id: 'fullstack',
    title: 'Full Stack Developer Roadmap',
    status: 'coming-soon',
    icon: '🧩',
    grad: 'linear-gradient(135deg, #F59E0B, #F97316)',
    tint: 'rgba(245, 158, 11, 0.12)',
    border: 'rgba(245, 158, 11, 0.35)',
    tagline: 'Frontend + Backend + Databases + Deployment. Build entire applications from design to production.',
    desc: 'The complete journey from one end of the stack to the other. You will build whole products — not just half of them.',
    meta: [{ label: '2 Paths', value: 'Combined' }, { label: '12+ Projects', value: 'Planned' }],
    href: null,
    cta: 'Coming Soon',
    soonNote: null
  },
  {
    id: 'dsa',
    title: 'Algorithms & Problem Solving',
    status: 'coming-soon',
    icon: '🧠',
    grad: 'linear-gradient(135deg, #10B981, #3B82F6)',
    tint: 'rgba(16, 185, 129, 0.12)',
    border: 'rgba(16, 185, 129, 0.35)',
    tagline: 'Data structures, algorithms, and the problem-solving mindset behind every strong interviewer.',
    desc: 'Arrays, linked lists, trees, recursion, sorting and searching — explained with visual examples and real challenges that build real thinking.',
    meta: [{ label: '40+ Challenges', value: 'Planned' }, { label: '5 Levels', value: 'Structured' }],
    href: null,
    cta: 'Coming Soon',
    soonNote: null
  },
  {
    id: 'devops',
    title: 'DevOps & Cloud Roadmap',
    status: 'coming-soon',
    icon: '☁️',
    grad: 'linear-gradient(135deg, #EC4899, #8B5CF6)',
    tint: 'rgba(236, 72, 153, 0.12)',
    border: 'rgba(236, 72, 153, 0.35)',
    tagline: 'Linux, Docker, CI/CD, and cloud deployment. Make your applications survive the real world.',
    desc: '"But it works on my machine" ends here. Learn to build, test, ship, and monitor software like a professional operations team.',
    meta: [{ label: '8 Levels', value: 'Planned' }, { label: 'Live Deploys', value: 'Target' }],
    href: null,
    cta: 'Coming Soon',
    soonNote: null
  },
  {
    id: 'mobile',
    title: 'Mobile Development',
    status: 'coming-soon',
    icon: '📱',
    grad: 'linear-gradient(135deg, #F97316, #EF4444)',
    tint: 'rgba(249, 115, 22, 0.12)',
    border: 'rgba(249, 115, 22, 0.35)',
    tagline: 'Cross-platform mobile apps that people actually install and use.',
    desc: 'Build real mobile applications with modern frameworks, clean architecture, and APIs that connect to real backend services.',
    meta: [{ label: '1 Stack', value: 'Cross-platform' }, { label: '5 Apps', value: 'Planned' }],
    href: null,
    cta: 'Coming Soon',
    soonNote: null
  }
];