/* Chango — Backend Developer Roadmap data (12 levels) */
var BACKEND_LEVELS = [
  {
    num: '01',
    title: 'Programming Fundamentals',
    status: 'available',
    icon: '🧱',
    accent: '#8B5CF6',
    gradient: 'linear-gradient(135deg, #8B5CF6, #6C3CE1)',
    tint: 'rgba(139, 92, 246, 0.14)',
    border: 'rgba(139, 92, 246, 0.4)',
    tagline: 'LEVEL 01',
    desc: 'The foundation every backend developer secretly wishes they built properly the first time. Variables, data types, conditionals, and loops.',
    time: '1–2 weeks',
    difficulty: 'Beginner',
    project: 'Console calculator',
    chapters: 'Book Chapter 1',
    topics: ['Variables', 'Data Types', 'Operators', 'If / Else', 'Loops'],
    href: 'lesson.html?level=programming&lesson=what-is-programming',
    cta: 'Start Level 01 →',
    lessonSlugs: ['what-is-programming', 'variables', 'data-types', 'conditionals', 'loops']
  },
  {
    num: '02',
    title: 'PHP',
    status: 'available',
    icon: '🐘',
    accent: '#6C3CE1',
    gradient: 'linear-gradient(135deg, #8B5CF6, #4F46E5)',
    tint: 'rgba(108, 60, 225, 0.14)',
    border: 'rgba(108, 60, 225, 0.4)',
    tagline: 'LEVEL 02',
    desc: 'Welcome to PHP. Yes, the elephant is part of the family. 🐘 The language that quietly powers a giant share of the internet.',
    time: '2–3 weeks',
    difficulty: 'Beginner',
    project: 'User registration system',
    chapters: 'Book Chapter 2',
    topics: ['Syntax', 'Functions', 'Arrays', 'Forms', 'Sessions', 'Files'],
    href: 'lesson.html?level=programming&lesson=php-syntax',
    cta: 'Start Level 02 →',
    lessonSlugs: ['php-syntax', 'php-functions', 'php-arrays', 'php-forms', 'php-sessions', 'php-files', 'php-errors', 'php-oop', 'php-dates', 'php-mysql']
  },
  {
    num: '03',
    title: 'Git & GitHub',
    status: 'available',
    icon: '🔀',
    accent: '#F97316',
    gradient: 'linear-gradient(135deg, #F97316, #F59E0B)',
    tint: 'rgba(249, 115, 22, 0.14)',
    border: 'rgba(249, 115, 22, 0.4)',
    tagline: 'LEVEL 03',
    desc: 'Stop creating final.zip, final2.zip, final_REAL.zip, final_REAL_v2.zip, final_REAL_FINAL.zip. Git exists for a reason.',
    time: '1 week',
    difficulty: 'Beginner',
    project: 'Versioned portfolio repo',
    chapters: 'Book Chapter 3',
    topics: ['Commit', 'Branch', 'Merge', 'GitHub', 'Pull Requests', 'Conflict resolution'],
    href: 'lesson.html?level=programming&lesson=git-why',
    cta: 'Start Level 03 →',
    lessonSlugs: ['git-why', 'git-commits', 'git-branches', 'git-github', 'git-prs']
  },
  {
    num: '04',
    title: 'SQL & Databases',
    status: 'available',
    icon: '🗄️',
    accent: '#22D3EE',
    gradient: 'linear-gradient(135deg, #22D3EE, #3B82F6)',
    tint: 'rgba(34, 211, 238, 0.14)',
    border: 'rgba(34, 211, 238, 0.4)',
    tagline: 'LEVEL 04',
    desc: 'Because storing your entire application inside a TXT file was... ambitious. Learn how data is really stored, queried, and related.',
    time: '2–3 weeks',
    difficulty: 'Intermediate',
    project: 'E-commerce database design',
    chapters: 'Book Chapter 4',
    topics: ['SELECT', 'JOIN', 'Relationships', 'Indexes', 'Normalization', 'CRUD'],
    href: 'lesson.html?level=programming&lesson=sql-what',
    cta: 'Start Level 04 →',
    lessonSlugs: ['sql-what', 'sql-select', 'sql-crud', 'sql-joins', 'sql-relationships', 'sql-indexes', 'sql-normalization', 'sql-design', 'sql-aggregation', 'sql-ecommerce']
  },
  {
    num: '05',
    title: 'Laravel',
    status: 'available',
    icon: '⚡',
    accent: '#F97316',
    gradient: 'linear-gradient(135deg, #F97316, #E11D48)',
    tint: 'rgba(249, 115, 22, 0.14)',
    border: 'rgba(249, 115, 22, 0.4)',
    tagline: 'LEVEL 05',
    desc: 'The framework that makes PHP feel like a luxury hotel instead of a hostel. Routing, Eloquent, migrations, Blade, and middleware.',
    time: '3–4 weeks',
    difficulty: 'Intermediate',
    project: 'Blog CMS',
    chapters: 'Book Chapter 5',
    topics: ['Routing', 'Controllers', 'Migrations', 'Eloquent', 'Blade', 'Validation', 'Auth'],
    href: 'lesson.html?level=programming&lesson=laravel-what',
    cta: 'Start Level 05 →',
    lessonSlugs: ['laravel-what', 'laravel-install', 'laravel-routing', 'laravel-controllers', 'laravel-blade', 'laravel-migrations', 'laravel-eloquent', 'laravel-validation', 'laravel-forms', 'laravel-auth', 'laravel-middleware', 'laravel-upload', 'laravel-storage', 'laravel-components', 'laravel-container']
  },
  {
    num: '06',
    title: 'REST APIs',
    status: 'available',
    icon: '🔗',
    accent: '#10B981',
    gradient: 'linear-gradient(135deg, #10B981, #3B82F6)',
    tint: 'rgba(16, 185, 129, 0.14)',
    border: 'rgba(16, 185, 129, 0.4)',
    tagline: 'LEVEL 06',
    desc: 'Your frontend wants data. Your database has data. The API is the awkward friend introducing them.',
    time: '2–3 weeks',
    difficulty: 'Intermediate',
    project: 'Todo API',
    chapters: 'Book Chapter 6',
    topics: ['HTTP', 'Routes', 'Resources', 'Status codes', 'Postman', 'Testing APIs'],
    href: 'lesson.html?level=programming&lesson=api-what',
    cta: 'Start Level 06 →',
    lessonSlugs: ['api-what', 'api-http', 'api-routes', 'api-resources', 'api-status', 'api-postman', 'api-pagination', 'api-search']
  },
  {
    num: '07',
    title: 'Authentication & Security',
    status: 'available',
    icon: '🔐',
    accent: '#EC4899',
    gradient: 'linear-gradient(135deg, #EC4899, #8B5CF6)',
    tint: 'rgba(236, 72, 153, 0.14)',
    border: 'rgba(236, 72, 153, 0.4)',
    tagline: 'LEVEL 07',
    desc: '"The user" is not a villain. But locking your app behind working auth & security still matters. Sanctum, tokens, CSRF, and friends.',
    time: '2 weeks',
    difficulty: 'Advanced',
    project: 'Secure login API',
    chapters: 'Book Chapter 7',
    topics: ['Hashing', 'Sanctum', 'Tokens', 'CSRF', 'XSS', 'Roles & Policies'],
    href: 'lesson.html?level=programming&lesson=security-hashing',
    cta: 'Start Level 07 →',
    lessonSlugs: ['security-hashing', 'security-sanctum', 'security-csrf', 'security-xss', 'security-roles', 'security-api-auth', 'security-rate-limit', 'security-checklist']
  },
  {
    num: '08',
    title: 'Linux',
    status: 'available',
    icon: '🐧',
    accent: '#FBBF24',
    gradient: 'linear-gradient(135deg, #F59E0B, #EF4444)',
    tint: 'rgba(245, 158, 11, 0.14)',
    border: 'rgba(245, 158, 11, 0.4)',
    tagline: 'LEVEL 08',
    desc: 'In production, there is no Start menu. Learn the terminal commands that every backend developer must not be afraid of.',
    time: '1–2 weeks',
    difficulty: 'Intermediate',
    project: 'Server environment setup',
    chapters: 'Book Chapter 8',
    topics: ['Terminal', 'File system', 'Permissions', 'Processes', 'SSH', 'Cron'],
    href: 'lesson.html?level=programming&lesson=linux-terminal',
    cta: 'Start Level 08 →',
    lessonSlugs: ['linux-terminal', 'linux-files', 'linux-processes', 'linux-ssh', 'linux-cron']
  },
  {
    num: '09',
    title: 'Docker',
    status: 'available',
    icon: '🐳',
    accent: '#3B82F6',
    gradient: 'linear-gradient(135deg, #3B82F6, #2563EB)',
    tint: 'rgba(59, 130, 246, 0.14)',
    border: 'rgba(59, 130, 246, 0.4)',
    tagline: 'LEVEL 09',
    desc: '"But it works on my machine." — Every developer before Docker. Containers are how we stop that sentence forever.',
    time: '1–2 weeks',
    difficulty: 'Intermediate',
    project: 'Dockerized Laravel app',
    chapters: 'Book Chapter 9',
    topics: ['Images', 'Containers', 'Dockerfile', 'docker-compose', 'Volumes'],
    href: 'lesson.html?level=programming&lesson=docker-why',
    cta: 'Start Level 09 →',
    lessonSlugs: ['docker-why', 'docker-images', 'dockerfile', 'docker-compose', 'docker-laravel']
  },
  {
    num: '10',
    title: 'Deployment',
    status: 'available',
    icon: '🚀',
    accent: '#EF4444',
    gradient: 'linear-gradient(135deg, #EF4444, #F97316)',
    tint: 'rgba(239, 68, 68, 0.14)',
    border: 'rgba(239, 68, 68, 0.4)',
    tagline: 'LEVEL 10',
    desc: 'The moment your code goes public and your console becomes a support line. Learn to deploy without setting anything on fire.',
    time: '1–2 weeks',
    difficulty: 'Advanced',
    project: 'Live deployed backend',
    chapters: 'Book Chapter 10',
    topics: ['Shared hosting', 'VPS', 'Nginx', 'Env vars', 'HTTPS', 'Logs'],
    href: 'lesson.html?level=programming&lesson=deploy-hosting',
    cta: 'Start Level 10 →',
    lessonSlugs: ['deploy-hosting', 'deploy-vps', 'deploy-nginx', 'deploy-env', 'deploy-https']
  },
  {
    num: '11',
    title: 'Real Projects',
    status: 'available',
    icon: '🏗️',
    accent: '#10B981',
    gradient: 'linear-gradient(135deg, #10B981, #F59E0B)',
    tint: 'rgba(16, 185, 129, 0.14)',
    border: 'rgba(16, 185, 129, 0.4)',
    tagline: 'LEVEL 11',
    desc: 'Time to prove it. Build real backend systems: a Blog API, an E-Commerce API, and finally the Job Marketplace API.',
    time: '4–6 weeks',
    difficulty: 'Advanced',
    project: 'Job Marketplace API',
    chapters: 'Book Chapter 11',
    topics: ['Todo API', 'Blog API', 'Auth API', 'E-Commerce API', 'Job Marketplace API'],
    href: 'projects.html',
    cta: 'View Projects →',
    lessonSlugs: ['projects-todo', 'projects-blog', 'projects-auth', 'projects-ecommerce', 'projects-job-market', 'projects-portfolio']
  },
  {
    num: '12',
    title: 'Job Ready',
    status: 'available',
    icon: '💼',
    accent: '#6C3CE1',
    gradient: 'linear-gradient(135deg, #8B5CF6, #EC4899)',
    tint: 'rgba(139, 92, 246, 0.14)',
    border: 'rgba(139, 92, 246, 0.4)',
    tagline: 'LEVEL 12',
    desc: 'The final boss. Portfolio, CV, GitHub profile, interview questions, and the mindset to survive a real job interview.',
    time: 'Ongoing',
    difficulty: 'Career',
    project: 'Your public profile',
    chapters: 'Book Chapter 12',
    topics: ['Portfolio', 'CV', 'GitHub', 'Interviews', 'Salary talk', 'First job'],
    href: 'lesson.html?level=programming&lesson=job-portfolio',
    cta: 'Start Level 12 →',
    lessonSlugs: ['job-portfolio', 'job-github', 'job-cv', 'job-interview', 'job-first-job']
  }
];

var BACKEND_TOTAL_LESSONS = 87;